/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#d89b1ace9f4dc1f4a0a76e585746fa5be7c6eb5b
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
let _initProto, _DoctypeTagDecs, _ReferenceTagDecs, _GapTagDecs, _ShiftTagDecs, _NullTagDecs, _ArrayInitializerTagDecs, _NodeDecs, _PropertyDecs, _OpenNodeTagDecs, _OpenFragmentTagDecs, _CloseNodeTagDecs, _CloseFragmentTagDecs, _BooleanAttributeDecs, _MappingAttributeDecs, _IdentifierPathDecs, _StringDecs, _LiteralTagDecs, _NumberDecs, _IntegerDecs, _BooleanDecs, _InfinityDecs, _PunctuatorDecs, _KeywordDecs, _AnyDecs;
import { re, spam as m } from '@bablr/boot';
import { Node, CoveredBy, InjectFrom, Attributes, UnboundAttributes, AllowEmpty } from '@bablr/helpers/decorators';
import { o } from '@bablr/agast-vm-helpers/embed';
import { eat, eatMatch, match, bindAttribute, fail } from '@bablr/helpers/grammar';
import { notNull } from '@bablr/agast-helpers/tree';
import { buildBoolean, buildNullTag, buildString } from '@bablr/agast-vm-helpers';
import * as productions from '@bablr/helpers/productions';
import * as Space from '@bablr/language-en-blank-space';
export const canonicalURL = 'https://bablr.org/languages/core/en/cstml';
export const dependencies = {
  Space
};
const escapables = new Map(Object.entries({
  n: '\n',
  r: '\r',
  t: '\t',
  0: '\0'
}));
export const getCooked = (escapeNode, span, ctx) => {
  let cooked;
  const codeNode = escapeNode.get('code');
  const type = ctx.sourceTextFor(codeNode.get('typeToken'));
  const value = ctx.sourceTextFor(codeNode.get('value'));
  if (!span.startsWith('String')) {
    throw new Error('not implemented');
  }
  if (!type) {
    const match_ = ctx.sourceTextFor(codeNode);
    cooked = escapables.get(match_) || match_;
  } else if (type === 'u') {
    cooked = parseInt(value, 16);
  } else {
    throw new Error();
  }
  return cooked.toString(10);
};
export function* eatMatchTrivia() {
  if (yield match(re`/[ \t\r\n]/`)) {
    return yield eat(m`#: <*Space:Space />`);
  }
  return null;
}
export const grammar = class CSTMLGrammar {
  static {
    [_initProto] = _applyDecs(this, [[Node, 2, "Document"], [_DoctypeTagDecs, 2, "DoctypeTag"], [_ReferenceTagDecs, 2, "ReferenceTag"], [[AllowEmpty, Node], 2, "ReferenceFlags"], [_GapTagDecs, 2, "GapTag"], [_ShiftTagDecs, 2, "ShiftTag"], [_NullTagDecs, 2, "NullTag"], [_ArrayInitializerTagDecs, 2, "ArrayInitializerTag"], [_NodeDecs, 2, "Node"], [Node, 2, "Fragment"], [_PropertyDecs, 2, "Property"], [[Node, AllowEmpty], 2, "NodeFlags"], [_OpenNodeTagDecs, 2, "OpenNodeTag"], [_OpenFragmentTagDecs, 2, "OpenFragmentTag"], [AllowEmpty, 2, "Attributes"], [_CloseNodeTagDecs, 2, "CloseNodeTag"], [_CloseFragmentTagDecs, 2, "CloseFragmentTag"], [_BooleanAttributeDecs, 2, "BooleanAttribute"], [_MappingAttributeDecs, 2, "MappingAttribute"], [AllowEmpty, 2, "TagType"], [_IdentifierPathDecs, 2, "IdentifierPath"], [_StringDecs, 2, "String"], [[AllowEmpty, Node], 2, "StringContent"], [Node, 2, "EscapeSequence"], [Node, 2, "EscapeCode"], [Node, 2, "Identifier"], [_LiteralTagDecs, 2, "LiteralTag"], [_NumberDecs, 2, "Number"], [Node, 2, "UnsignedInteger"], [_IntegerDecs, 2, "Integer"], [_BooleanDecs, 2, "Boolean"], [_InfinityDecs, 2, "Infinity"], [_PunctuatorDecs, 2, "Punctuator"], [_KeywordDecs, 2, "Keyword"], [_AnyDecs, 2, "Any"]], []).e;
  }
  constructor() {
    _initProto(this);
  }
  *[(_DoctypeTagDecs = [CoveredBy('Tag'), CoveredBy('Expression'), Node], _ReferenceTagDecs = [Node, CoveredBy('Tag'), CoveredBy('Expression')], _GapTagDecs = [Node, CoveredBy('Tag'), CoveredBy('Expression'), CoveredBy('PropertyValue')], _ShiftTagDecs = [Node, CoveredBy('Tag')], _NullTagDecs = [Node, CoveredBy('Tag'), CoveredBy('Expression'), CoveredBy('PropertyValue')], _ArrayInitializerTagDecs = [Node, CoveredBy('Tag'), CoveredBy('PropertyValue')], _NodeDecs = [Node, CoveredBy('PropertyValue')], _PropertyDecs = [Node, CoveredBy('NodeChild'), CoveredBy('FragmentChild')], _OpenNodeTagDecs = [UnboundAttributes(['balanced', 'balancedSpan']), Node, CoveredBy('Tag'), CoveredBy('OpenTag')], _OpenFragmentTagDecs = [Attributes({
    balanced: true,
    balancedSpan: 'FragmentChildren'
  }), Node, CoveredBy('Tag'), CoveredBy('OpenTag')], _CloseNodeTagDecs = [Attributes({
    balancer: true
  }), Node, CoveredBy('Tag'), CoveredBy('CloseTag')], _CloseFragmentTagDecs = [Attributes({
    balancer: true
  }), Node, CoveredBy('Tag'), CoveredBy('CloseTag')], _BooleanAttributeDecs = [UnboundAttributes(['true']), Node, CoveredBy('Attribute')], _MappingAttributeDecs = [Node, CoveredBy('Attribute')], _IdentifierPathDecs = [CoveredBy('Language'), Node], _StringDecs = [CoveredBy('AttributeValue'), CoveredBy('Language'), Node], _LiteralTagDecs = [Node, CoveredBy('Tag'), CoveredBy('Expression'), CoveredBy('NodeChild'), CoveredBy('FragmentChild')], _NumberDecs = CoveredBy('AttributeValue'), _IntegerDecs = [CoveredBy('Number'), Node], _BooleanDecs = [CoveredBy('AttributeValue'), Node], _InfinityDecs = [CoveredBy('Number'), Node], _PunctuatorDecs = [Node, InjectFrom(productions)], _KeywordDecs = [Node, InjectFrom(productions)], _AnyDecs = InjectFrom(productions), Symbol.for('@bablr/fragment'))]() {
    yield* eatMatchTrivia();
    yield eat(m`<? />`);
    yield* eatMatchTrivia();
  }
  *Stream() {
    while (yield eatMatch(m`.[]: <Tag>`));
  }
  *Expression() {
    yield eat(m`<Any />`, [m`<NullTag 'null' />`, m`<ReferenceTag /\.|[a-zA-Z]/ />`, m`<LiteralTag /['"]/ />`, m`<DoctypeTag '<!' />`, m`<GapTag '<//>' />`, m`<Node '<' />`]);
  }
  *Tag() {
    yield eat(m`<Any />`, [m`<NullTag 'null' />`, m`<ArrayInitializerTag '[]' />`, m`<ReferenceTag /\.|[a-zA-Z]/ />`, m`<LiteralTag /['"]/ />`, m`<DoctypeTag '<!' />`, m`<GapTag '<//>' />`, m`<ShiftTag '^^^' />`, m`<CloseTag '</' />`, m`<OpenTag '<' />`]);
  }
  *Document() {
    yield eat(m`doctype$: <DoctypeTag />`);
    yield* eatMatchTrivia();
    yield eat(m`tree$: <Fragment />`);
  }
  *DoctypeTag() {
    yield eat(m`openToken: <*Punctuator '<!' balancedSpan='Tag' balanced='>' />`);
    yield eat(m`version$: <*UnsignedInteger />`);
    yield eat(m`versionSeparatorToken: <*Punctuator ':' />`);
    yield eat(m`doctypeToken$: <*Keyword 'cstml' />`);
    yield* eatMatchTrivia();
    yield eat(m`attributes[]$: <Attributes />`);
    yield eat(m`closeToken: <*Punctuator '>' balancer />`);
  }
  *ReferenceTag() {
    let quot;
    if (quot = yield match(re`/[.#@]/`)) {
      yield eat(m`name$: <*Punctuator ${quot} />`);
    } else {
      yield eat(m`name$: <*Identifier />`);
    }
    yield* eatMatchTrivia();
    if (yield eatMatch(m`openIndexToken: <*Punctuator '[' balanced=']' />`)) {
      yield* eatMatchTrivia();
      yield eatMatch(m`index: <UnsignedInteger />`);
      yield* eatMatchTrivia();
      yield eatMatch(m`closeIndexToken: <*Punctuator ']' balancer />`);
    }
    yield* eatMatchTrivia();
    yield eat(m`refFlags: <ReferenceFlags />`);
    yield* eatMatchTrivia();
    yield eat(m`sigilToken: <*Punctuator ':' />`);
  }
  *ReferenceFlags() {
    yield eatMatch(m`expressionToken: <*Punctuator '+' />`);
    yield eatMatch(m`hasGapToken: <*Punctuator '$' />`);
  }
  *GapTag() {
    yield eat(m`sigilToken: <*Punctuator '<//>' />`);
  }
  *ShiftTag() {
    yield eat(m`sigilToken: <*Punctuator '^^^' />`);
  }
  *NullTag() {
    yield eat(m`sigilToken: <*Keyword 'null' />`);
  }
  *ArrayInitializerTag() {
    yield eat(m`sigilToken: <*Punctuator '[]' />`);
  }
  *Node() {
    let open = yield eat(m`open: <OpenNodeTag />`);
    yield* eatMatchTrivia();

    // Problem: not handling gaps
    //   gaps have a non-nullish representation
    //

    const flags = open.get('flags');
    const selfClosingTagToken = open.get('selfClosingTagToken');
    const token = notNull(flags.get('tokenToken'));
    const selfClosing = notNull(selfClosingTagToken);
    yield eat(m`children[]$: []`);
    if (selfClosing) {
      yield eat(m`close: null`);
    } else {
      while ((yield match(re`/./`)) && !(yield match('</'))) {
        yield eat(m`children[]$: <NodeChild />`, o({
          token: buildBoolean(token)
        }));
        yield* eatMatchTrivia();
      }
      yield eat(m`close: <CloseNodeTag />`);
    }
  }
  *Fragment() {
    let open = yield eat(m`open: <OpenFragmentTag />`);
    yield* eatMatchTrivia();
    const flags = open.get('flags');
    const token = notNull(flags.get('tokenToken'));
    yield eat(m`children[]$: []`);
    while ((yield match(re`/./`)) && !(yield match('</'))) {
      yield eat(m`children[]$: <FragmentChild />`, o({
        token: buildBoolean(token)
      }));
      yield* eatMatchTrivia();
    }
    yield eat(m`close: <CloseFragmentTag />`);
  }
  *NodeChild({
    value: props,
    ctx
  }) {
    const {
      token
    } = ctx.unbox(props || {});
    if (token && ctx.unbox(token)) {
      yield eat(m`<Any />`, [m`<Node /\<\*?@/ />`, m`<LiteralTag /['"]/ />`]);
    } else {
      yield eat(m`<Any />`, [m`<Node /\<\*?#/ />`, m`<Property /\.|[a-zA-Z]/ />`, m`<ShiftTag '^^^' />`]);
    }
  }
  *FragmentChild({
    value: props,
    ctx
  }) {
    const {
      token
    } = ctx.unbox(props || {});
    if (token && ctx.unbox(token)) {
      yield eat(m`<Any />`, [m`<Node /\<\*?@/ />`, m`<LiteralTag /['"]/ />`]);
    } else {
      yield eat(m`<Any />`, [m`<Node /\<\*?#/ />`, m`<Property /\.|[a-zA-Z]/ />`]);
    }
  }
  *Property() {
    yield eat(m`reference: <ReferenceTag />`);
    yield* eatMatchTrivia();
    yield eat(m`value: <PropertyValue />`);
  }
  *PropertyValue() {
    yield eat(m`<Any />`, [m`<NullTag 'null' />`, m`<GapTag '<//>' />`, m`<ArrayInitializerTag '[]' />`, m`<Node /\<[^#@]/ />`]);
  }
  *NodeFlags() {
    yield eatMatch(m`tokenToken: <*Punctuator '*' />`);
    yield eatMatch(m`hasGapToken: <*Punctuator '$' />`);
  }
  *OpenTag({
    s
  }) {
    if (s.span === 'NodeChildren' || s.span === 'FragmentChildren') {
      yield eat(s`<OpenNodeTag />`);
    } else if (s.span === 'Bare' || s.span === 'Stream') {
      yield eat(s`<OpenFragmentTag />`);
    } else {
      yield fail();
    }
  }
  *OpenNodeTag({
    s
  }) {
    const outerSpan = s.span;
    yield eat(s`openToken: <*Punctuator '<' balancedSpan='Tag' balanced='>' />`);
    let flags = yield eat(s`flags: <NodeFlags />`);
    yield eat(s`<TagType />`);
    let sp = yield* eatMatchTrivia();
    if (sp && flags.get('tokenToken') && (yield match(re`/['"]/`))) {
      yield eat(s`intrinsicValue$: <String />`);
      sp = yield* eatMatchTrivia();
    } else {
      yield eat(s`intrinsicValue$: null`);
    }
    yield eat(s`attributes[]$: <Attributes />`);
    let sc = yield eatMatch(s`selfClosingTagToken: <*Punctuator '/' />`);
    const balanced = !sc && (s.path.depth > 1 || outerSpan !== 'Bare');
    yield bindAttribute('balanced', buildBoolean(balanced));
    yield bindAttribute('balancedSpan', balanced ? buildString('NodeChildren') : buildNullTag());
    yield eat(s`closeToken: <*Punctuator '>' balancer />`);
  }
  *OpenFragmentTag() {
    yield eat(m`openToken: <*Punctuator '<' balancedSpan='Tag' balanced='>' />`);
    yield eat(m`flags: <NodeFlags />`);
    yield eat(m`closeToken: <*Punctuator '>' balancer />`);
  }
  *Attributes() {
    yield eat(m`.[]$: []`);
    let sp = true;
    while (sp && (yield match(re`/!?[a-zA-Z]|\g/`))) {
      yield eat(m`.[]$: <Attribute />`);
      sp = yield* eatMatchTrivia();
    }
  }
  *CloseTag({
    s
  }) {
    if (s.span === 'NodeChildren') {
      yield eat(s`<CloseNodeTag />`);
    } else if (s.span === 'FragmentChildren') {
      yield eat(s`<CloseFragmentTag />`);
    } else {
      yield fail();
    }
  }
  *CloseNodeTag() {
    yield eat(m`openToken: <*Punctuator '</' balanced='>' />`);
    yield eat(m`<TagType />`);
    yield eat(m`closeToken: <*Punctuator '>' balancer />`);
  }
  *CloseFragmentTag() {
    yield eat(m`openToken: <*Punctuator '</' balanced='>' />`);
    yield eat(m`closeToken: <*Punctuator '>' balancer />`);
  }
  *Attribute() {
    if (yield match(re`/([a-zA-Z][a-zA-Z_-]*|\g)\s*=/`)) {
      yield eat(m`<MappingAttribute />`);
    } else {
      yield eat(m`<BooleanAttribute />`);
    }
  }
  *BooleanAttribute() {
    if (yield eatMatch(m`negateToken: <*Punctuator '!' />`)) {
      yield bindAttribute('true', false);
    } else {
      yield bindAttribute('true', true);
    }
    yield eat(m`key$: <*Identifier />`);
  }
  *MappingAttribute() {
    yield eat(m`key$: <*Identifier />`);
    yield* eatMatchTrivia();
    yield eat(m`sigilToken: <*Punctuator '=' />`);
    yield* eatMatchTrivia();
    yield eat(m`value$: <AttributeValue />`);
  }
  *AttributeValue() {
    yield eat(m`<Any />`, [m`<String /['"]/ />`, m`<Number /[\d+-]/ />`, m`<Boolean /true|false/ />`]);
  }
  *TagType() {
    if (yield match(re`/['"]|([a-zA-Z.]+|\g):/`)) {
      yield eat(m`language$: <Language />`);
      yield eat(m`namespaceSeparatorToken: <*Punctuator ':' />`);
      yield eat(m`type$: <*Identifier />`);
    } else if (yield match(re`/[a-zA-Z]/`)) {
      yield eat(m`language$: null`);
      yield eat(m`type$: <*Identifier />`);
    } else {
      yield eat(m`language$: null`);
      yield eat(m`type$: null`);
    }
  }
  *Language() {
    yield eat(m`<Any />`, [m`<String /['"]/ />`, m`<IdentifierPath /[a-zA-Z]/ />`]);
  }
  *IdentifierPath() {
    yield eat(m`segments[]$: <*Identifier />`);
    while (yield match('.')) {
      yield eat(m`separators[]: <*Punctuator '.' />`);
      yield eat(m`segments[]$: <*Identifier />`);
    }
  }
  *String({
    ctx
  }) {
    let q = yield match(re`/['"]/`);
    if (!q) yield fail();
    const q_ = ctx.sourceTextFor(q);
    yield q_ === "'" ? eat(m`openToken: <*Punctuator "'" balanced="'" balancedSpan='String:Single' />`) : eat(m`openToken: <*Punctuator '"' balanced='"' balancedSpan='String:Double' />`);
    yield eat(m`content: <*StringContent />`);
    yield q_ === "'" ? eat(m`closeToken: <*Punctuator "'" balancer />`) : eat(m`closeToken: <*Punctuator '"' balancer />`);
  }
  *StringContent({
    state: {
      span
    }
  }) {
    let esc, lit;
    do {
      esc = (yield match('\\')) && (yield eat(m`@: <EscapeSequence />`));
      lit = span === 'String:Single' ? yield eatMatch(re`/[^\r\n\\'\g]+/`) : yield eatMatch(re`/[^\r\n\\"\g]+/`);
    } while (esc || lit);
  }
  *EscapeSequence({
    state: {
      span
    },
    ctx
  }) {
    if (!span.startsWith('String')) {
      yield fail();
    }
    yield eat(m`escapeToken: <*Punctuator '\\' openSpan='Escape' />`);
    let match;
    if (match = span === 'String:Single' ? yield match(re`/[\\/nrt0']/`) : yield match(re`/[\\/nrt0"]/`)) {
      const match_ = ctx.sourceTextFor(match);
      yield eat(m`code: <*Keyword ${buildString(match_)} closeSpan='Escape' />`);
    } else if (yield match('u')) {
      yield eat(m`code: <EscapeCode closeSpan='Escape' />`);
    } else {
      yield fail();
    }
  }
  *EscapeCode() {
    if (yield eatMatch(m`typeToken: <*Keyword 'u' />`)) {
      if (yield eatMatch(m`openToken: <*Punctuator '{' balanced='}' />`)) {
        yield eat(m`value$: <*UnsignedInteger />`);
        yield eat(m`closeToken: <*Punctuator '}' balancer />`);
      } else {
        yield eat(m`value$: <*UnsignedInteger /\d{4}/ />`);
        yield eat(m`closeToken: null`);
      }
    }
  }
  *Identifier() {
    yield eat(re`/[a-zA-Z][a-zA-Z_-]*/`);
  }
  *LiteralTag() {
    yield eat(m`value: <String />`);
  }
  *Number() {
    yield eat(m`<Any />`, [m`<Integer /-?\d/ />`, m`<Infinity /[+-]I/ />`]);
  }
  *UnsignedInteger() {
    yield eat(re`/\d+/`);
  }
  *Integer() {
    yield eatMatch(m`signToken: <*Punctuator '-' />`);
    yield eat(m`value: <*UnsignedInteger />`);
  }
  *Boolean() {
    yield eatMatch(m`sigilToken: <*Keyword /true|false/ />`);
  }
  *Infinity() {
    yield eatMatch(m`signToken: <*Punctuator /[+-]/ />`);
    yield eat(m`sigilToken: <*Keyword 'Infinity' />`);
  }
  *Punctuator() {}
  *Keyword() {}
  *Any() {}
};