/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#95a4cf62d3fd5bf71eea24c40d7cb08f75d1750e
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
let _initProto, _DoctypeTagDecs, _ReferenceTagDecs, _GapTagDecs, _ShiftTagDecs, _NullTagDecs, _ArrayInitializerTagDecs, _NodeDecs, _PropertyDecs, _OpenNodeTagDecs, _OpenFragmentTagDecs, _CloseNodeTagDecs, _CloseFragmentTagDecs, _IdentifierPathDecs, _LiteralTagDecs, _PunctuatorDecs, _KeywordDecs, _AnyDecs;
import { re, spam as m } from '@bablr/boot';
import { Node, CoveredBy, InjectFrom, Attributes, UnboundAttributes, AllowEmpty } from '@bablr/helpers/decorators';
import { e, eat, eatMatch, match, bindAttribute, fail, extendLanguage } from '@bablr/helpers/grammar';
import { notNull } from '@bablr/agast-helpers/tree';
import { buildBoolean, buildIdentifier, buildNull, buildString } from '@bablr/helpers/builders';
import * as productions from '@bablr/helpers/productions';
import * as Space from '@bablr/language-en-blank-space';
import * as JSON from '@bablr/language-en-cstml-json';
export const canonicalURL = 'https://bablr.org/languages/core/en/cstml';
const CSTMLJSON = extendLanguage(JSON, {
  dependencies: {
    CSTML: canonicalURL
  },
  grammar: class CSTMLJSON extends JSON.grammar {
    *Expression(props) {
      if (yield match('<')) {
        yield eat(m`<CSTML:Expression />`);
      } else {
        yield* super.Expression(props);
      }
    }
  }
});
export const dependencies = {
  Space,
  JSON: CSTMLJSON
};
const escapables = new Map(Object.entries({
  n: '\n',
  r: '\r',
  t: '\t',
  0: '\0'
}));
export const getCooked = (escapeNode, span, ctx) => {
  let cooked;
  const codeNode = escapeNode.get('code');
  const type = ctx.sourceTextFor(codeNode.get('typeToken'));
  const value = ctx.sourceTextFor(codeNode.get('value'));
  if (!span.startsWith('String')) {
    throw new Error('not implemented');
  }
  if (!type) {
    const match_ = ctx.sourceTextFor(codeNode);
    cooked = escapables.get(match_) || match_;
  } else if (type === 'u') {
    cooked = parseInt(value, 16);
  } else {
    throw new Error();
  }
  return cooked.toString(10);
};
export function* eatMatchTrivia() {
  if (yield match(re`/[ \t\r\n]/`)) {
    return yield eat(m`#: <*Space:Space />`);
  }
  return null;
}
export const grammar = class CSTMLGrammar {
  static {
    [_initProto] = _applyDecs(this, [[Node, 2, "Document"], [_DoctypeTagDecs, 2, "DoctypeTag"], [_ReferenceTagDecs, 2, "ReferenceTag"], [[AllowEmpty, Node], 2, "ReferenceFlags"], [_GapTagDecs, 2, "GapTag"], [_ShiftTagDecs, 2, "ShiftTag"], [_NullTagDecs, 2, "NullTag"], [_ArrayInitializerTagDecs, 2, "ArrayInitializerTag"], [_NodeDecs, 2, "Node"], [Node, 2, "Fragment"], [_PropertyDecs, 2, "Property"], [[Node, AllowEmpty], 2, "NodeFlags"], [_OpenNodeTagDecs, 2, "OpenNodeTag"], [_OpenFragmentTagDecs, 2, "OpenFragmentTag"], [_CloseNodeTagDecs, 2, "CloseNodeTag"], [_CloseFragmentTagDecs, 2, "CloseFragmentTag"], [AllowEmpty, 2, "TagType"], [_IdentifierPathDecs, 2, "IdentifierPath"], [Node, 2, "Identifier"], [_LiteralTagDecs, 2, "LiteralTag"], [_PunctuatorDecs, 2, "Punctuator"], [_KeywordDecs, 2, "Keyword"], [_AnyDecs, 2, "Any"]], []).e;
  }
  constructor() {
    _initProto(this);
  }
  *[(_DoctypeTagDecs = [CoveredBy('Tag'), CoveredBy('Expression'), Node], _ReferenceTagDecs = [Node, CoveredBy('Tag'), CoveredBy('Expression')], _GapTagDecs = [Node, CoveredBy('Tag'), CoveredBy('Expression'), CoveredBy('PropertyValue')], _ShiftTagDecs = [Node, CoveredBy('Tag')], _NullTagDecs = [Node, CoveredBy('Tag'), CoveredBy('Expression'), CoveredBy('PropertyValue')], _ArrayInitializerTagDecs = [Node, CoveredBy('Tag'), CoveredBy('PropertyValue')], _NodeDecs = [Node, CoveredBy('PropertyValue')], _PropertyDecs = [Node, CoveredBy('NodeChild'), CoveredBy('FragmentChild')], _OpenNodeTagDecs = [UnboundAttributes(['balanced', 'balancedSpan']), Node, CoveredBy('Tag'), CoveredBy('OpenTag')], _OpenFragmentTagDecs = [Attributes({
    balanced: true,
    balancedSpan: 'FragmentChildren'
  }), Node, CoveredBy('Tag'), CoveredBy('OpenTag')], _CloseNodeTagDecs = [Attributes({
    balancer: true
  }), Node, CoveredBy('Tag'), CoveredBy('CloseTag')], _CloseFragmentTagDecs = [Attributes({
    balancer: true
  }), Node, CoveredBy('Tag'), CoveredBy('CloseTag')], _IdentifierPathDecs = [CoveredBy('Language'), Node], _LiteralTagDecs = [Node, CoveredBy('Tag'), CoveredBy('Expression'), CoveredBy('NodeChild'), CoveredBy('FragmentChild')], _PunctuatorDecs = [Node, InjectFrom(productions)], _KeywordDecs = [Node, InjectFrom(productions)], _AnyDecs = InjectFrom(productions), Symbol.for('@bablr/fragment'))]({
    value: {
      productionName
    }
  }) {
    yield* eatMatchTrivia();
    yield eat(m`<${buildIdentifier(productionName)} />`);
    yield* eatMatchTrivia();
  }
  *Stream() {
    while (yield eatMatch(m`.[]: <Tag />`));
  }
  *Expression() {
    yield eat(m`<Any />`, e([m`<Document '<!' />`, m`<Node '<' />`]));
  }
  *Tag() {
    yield eat(m`<Any />`, e([m`<NullTag 'null' />`, m`<ArrayInitializerTag '[]' />`, m`<ReferenceTag /\.|[a-zA-Z]/ />`, m`<LiteralTag /['"]/ />`, m`<DoctypeTag '<!' />`, m`<GapTag '<//>' />`, m`<ShiftTag '^^^' />`, m`<CloseTag '</' />`, m`<OpenTag '<' />`]));
  }
  *Document() {
    yield eat(m`doctype$: <DoctypeTag />`);
    yield* eatMatchTrivia();
    yield eat(m`tree$: <Fragment />`);
  }
  *DoctypeTag() {
    yield eat(m`openToken: <*Punctuator '<!' { balancedSpan: 'Tag', balanced: '>' } />`);
    yield eat(m`version$: <*JSON:UnsignedInteger />`);
    yield eat(m`versionSeparatorToken: <*Punctuator ':' />`);
    yield eat(m`doctypeToken$: <*Keyword 'cstml' />`);
    yield* eatMatchTrivia();
    yield eatMatch(m`attributes$: <JSON:Object />`);
    yield eat(m`closeToken: <*Punctuator '>' { balancer: true } />`);
  }
  *ReferenceTag({
    ctx
  }) {
    let quot;
    if (quot = yield match(re`/[.#@]/`)) {
      yield eat(m`name$: <*Punctuator ${buildString(ctx.sourceTextFor(quot))} />`);
    } else {
      yield eat(m`name$: <*Identifier />`);
    }
    yield* eatMatchTrivia();
    if (yield eatMatch(m`openIndexToken: <*Punctuator '[' { balanced: ']' } />`)) {
      yield* eatMatchTrivia();
      yield eatMatch(m`index: <JSON:UnsignedInteger />`);
      yield* eatMatchTrivia();
      yield eatMatch(m`closeIndexToken: <*Punctuator ']' { balancer: true } />`);
    } else {
      yield eatMatch(m`closeIndexToken: null`);
    }
    yield* eatMatchTrivia();
    yield eat(m`flags: <ReferenceFlags />`);
    yield* eatMatchTrivia();
    yield eat(m`sigilToken: <*Punctuator ':' />`);
  }
  *ReferenceFlags() {
    yield eatMatch(m`expressionToken: <*Punctuator '+' />`);
    yield eatMatch(m`hasGapToken: <*Punctuator '$' />`);
  }
  *GapTag() {
    yield eat(m`sigilToken: <*Punctuator '<//>' />`);
  }
  *ShiftTag() {
    yield eat(m`sigilToken: <*Punctuator '^^^' />`);
  }
  *NullTag() {
    yield eat(m`sigilToken: <*Keyword 'null' />`);
  }
  *ArrayInitializerTag() {
    yield eat(m`sigilToken: <*Punctuator '[]' />`);
  }
  *Node() {
    let open = yield eat(m`open: <OpenNodeTag />`);
    yield* eatMatchTrivia();

    // Problem: not handling gaps
    //   gaps have a non-nullish representation
    //

    const flags = open.get('flags');
    const selfClosingTagToken = open.get('selfClosingTagToken');
    const token = notNull(flags.get('tokenToken'));
    const selfClosing = notNull(selfClosingTagToken);
    yield eat(m`children[]$: []`);
    if (selfClosing) {
      yield eat(m`close: null`);
    } else {
      while ((yield match(re`/./`)) && !(yield match('</'))) {
        yield eat(m`children[]$: <NodeChild />`, e({
          token: buildBoolean(token)
        }));
        yield* eatMatchTrivia();
      }
      yield eat(m`close: <CloseNodeTag />`);
    }
  }
  *Fragment() {
    let open = yield eat(m`open: <OpenFragmentTag />`);
    yield* eatMatchTrivia();
    const flags = open.get('flags');
    const token = notNull(flags.get('tokenToken'));
    yield eat(m`children[]$: []`);
    while ((yield match(re`/./`)) && !(yield match('</'))) {
      yield eat(m`children[]$: <FragmentChild />`, e({
        token: buildBoolean(token)
      }));
      yield* eatMatchTrivia();
    }
    yield eat(m`close: <CloseFragmentTag />`);
  }
  *NodeChild({
    value: props,
    ctx
  }) {
    const {
      token
    } = ctx.unbox(props || {});
    if (token && ctx.unbox(token)) {
      yield eat(m`<Any />`, e([m`<Property '@' />`, m`<LiteralTag /['"]/ />`]));
    } else {
      yield eat(m`<Any />`, e([m`<Property /[.#]|[a-zA-Z]/ />`, m`<ShiftTag '^^^' />`]));
    }
  }
  *FragmentChild({
    value: props,
    ctx
  }) {
    const {
      token
    } = ctx.unbox(props || {});
    if (token && ctx.unbox(token)) {
      yield eat(m`<Any />`, e([m`<Property '@' />`, m`<LiteralTag /['"]/ />`]));
    } else {
      yield eat(m`<Any />`, e([m`<Property /[.#]|[a-zA-Z]/ />`]));
    }
  }
  *Property() {
    yield eat(m`reference$: <ReferenceTag />`);
    yield* eatMatchTrivia();
    yield eat(m`value$: <PropertyValue />`);
  }
  *PropertyValue() {
    yield eat(m`<Any />`, e([m`<NullTag 'null' />`, m`<GapTag '<//>' />`, m`<ArrayInitializerTag '[]' />`, m`<Node /\<[^#@]/ />`]));
  }
  *NodeFlags() {
    yield eatMatch(m`tokenToken: <*Punctuator '*' />`);
    yield eatMatch(m`hasGapToken: <*Punctuator '$' />`);
  }
  *OpenTag({
    s
  }) {
    if (s.span === 'NodeChildren' || s.span === 'FragmentChildren') {
      yield eat(m`<OpenNodeTag />`);
    } else if (s.span === 'Bare' || s.span === 'Stream') {
      yield eat(m`<OpenFragmentTag />`);
    } else {
      yield fail();
    }
  }
  *OpenNodeTag({
    s
  }) {
    const outerSpan = s.span;
    yield eat(m`openToken: <*Punctuator '<' { balancedSpan: 'Tag', balanced: '>' } />`);
    let flags = yield eat(m`flags: <NodeFlags />`);
    yield eat(m`<TagType />`);
    let sp = yield* eatMatchTrivia();
    if (sp && flags.get('tokenToken') && (yield match(re`/['"]/`))) {
      yield eat(m`intrinsicValue$: <JSON:String />`);
      sp = yield* eatMatchTrivia();
    } else {
      yield eat(m`intrinsicValue$: null`);
    }
    yield eatMatch(m`attributes$: <JSON:Object />`);
    let sc = yield eatMatch(m`selfClosingTagToken: <*Punctuator '/' />`);
    const balanced = !sc && (s.depths.path > 0 || outerSpan !== 'Bare');
    yield bindAttribute('balanced', buildBoolean(balanced));
    yield bindAttribute('balancedSpan', balanced ? buildString('NodeChildren') : buildNull());
    yield eat(m`closeToken: <*Punctuator '>' { balancer: true } />`);
  }
  *OpenFragmentTag() {
    yield eat(m`openToken: <*Punctuator '<' { balancedSpan: 'Tag', balanced: '>' } />`);
    yield eat(m`flags: <NodeFlags />`);
    yield eat(m`closeToken: <*Punctuator '>' { balancer: true } />`);
  }
  *CloseTag({
    s
  }) {
    if (s.span === 'NodeChildren') {
      yield eat(m`<CloseNodeTag />`);
    } else if (s.span === 'FragmentChildren') {
      yield eat(m`<CloseFragmentTag />`);
    } else {
      yield fail();
    }
  }
  *CloseNodeTag() {
    yield eat(m`openToken: <*Punctuator '</' { balanced: '>' } />`);
    yield eat(m`closeToken: <*Punctuator '>' { balancer: true } />`);
  }
  *CloseFragmentTag() {
    yield eat(m`openToken: <*Punctuator '</' { balanced: '>' } />`);
    yield eat(m`closeToken: <*Punctuator '>' { balancer: true } />`);
  }
  *TagType() {
    if (yield match(re`/['"]|([a-zA-Z.]+|\g):/`)) {
      yield eat(m`language$: <Language />`);
      yield eat(m`namespaceSeparatorToken: <*Punctuator ':' />`);
      yield eat(m`type$: <*Identifier />`);
    } else if (yield match(re`/[a-zA-Z]/`)) {
      yield eat(m`language$: null`);
      yield eat(m`type$: <*Identifier />`);
    } else {
      yield eat(m`language$: null`);
      yield eat(m`type$: null`);
    }
  }
  *Language() {
    yield eat(m`<Any />`, e([m`<JSON:String /['"]/ />`, m`<IdentifierPath /[a-zA-Z]/ />`]));
  }
  *IdentifierPath() {
    yield eat(m`segments[]$: <*Identifier />`);
    while (yield match('.')) {
      yield eat(m`separatorTokens[]: <*Punctuator '.' />`);
      yield eat(m`segments[]$: <*Identifier />`);
    }
  }
  *Identifier() {
    yield eat(re`/[a-zA-Z][a-zA-Z_-]*/`);
  }
  *LiteralTag() {
    yield eat(m`value: <JSON:String />`);
  }
  *Punctuator() {}
  *Keyword() {}
  *Any() {}
};